site_name: Ridagop IDS Toolkit
nav:
  - Overview: index.md
  - technical_overview.md
  - "Schemas": schemas.md
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    - scheme: default
markdown_extensions:
  - attr_list
  - md_in_html
  - toc:
      permalink: "#"

repo_url: https://github.com/RIDAGOP-IDS-Toolkit
repo_name: GitHub