site_name: Ridagop IDS Toolkit
nav:
  - Overview: index.md
  - technical_overview.md
  - "Schemas": schemas.md
  - examples.md
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.tracking
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    - scheme: default
markdown_extensions:
  - attr_list
  - md_in_html
  - toc:
      permalink: "#"
  - admonition
  - pymdownx.details
  - pymdownx.superfences
plugins:
  - snippets
  - exclude:
      glob:
        - "*.md~"
        - snippets/*
repo_url: https://github.com/RIDAGOP-Toolkit
repo_name: GitHub